sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
    

  rabbitmq:
    host: 192.168.224.128
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8101

  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30

server:
  port: 8101

  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
   
management:
  endpoints:
    web:
      exposure:
        include: refresh

